Add subscription support for client
eclipsesource/modelserver pull request #33
Opened 2019-07-24 10:11 UTC by edgarmueller

2019-07-24 14:25 UTC, ndoschek requested changes
Looks good to me! The examples are very well documented and straight forward to use in a Java client.
One small issue came up when deleting a model which has subscribers (please see my comment).

2019-07-24 14:25 UTC, ndoschek commented on README.md
> +      .thenAccept(response -> System.out.println(response.body()))
Missing semicolon at line end

2019-07-24 14:25 UTC, ndoschek commented on README.md
> +      .thenAccept(response -> System.out.println(response.body()))
Missing semicolon at line end

2019-07-24 14:25 UTC, ndoschek commented on com.eclipsesource.modelserver.emf/src/main/java/com/eclipsesource/modelserver/emf/common/SessionController.java
> +						session.send(JsonResponse.data(encoder.encode(session, updatedModel)));
Broadcasting a deletion of a model which has subscribers throws exception: encoder expects EObject, but updateModel is null

Import of Context can be removed as well

2019-07-24 18:15 UTC, edgarmueller commented
@ndoschek Thanks for the review! I've updated the PR

2019-07-25 07:34 UTC, ndoschek approved these changes

2019-07-25 08:44 UTC, merged